@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/signup
Content-Type: application/json
Accept: application/json
Withcredentials: true

{
	"username":"test",
	"password":"test1",
	"email":"edgar.riveraj@gmail.com"
}
